### ISSUE TITLE
Critical bug: Norway is not on your bucket list

### ISSUE THREAD

**Issue by frewsxcv** [streeter/bucket-list#1]
![](http://nordictravel.com.au/image/type/galleryFullImage/id/4601/filename/geiranger3072005-99-3045-hm-4288x2848-300+c.Terje+Rakke_Innovation+Norway.jpg)

**Comment by streeter** [comment]
The repo started off as a better version of [this gist](https://gist.github.com/streeter/80a47672c29324608fce), and then I had to move it to a repo since the gist started breaking with longer lists and with my [recently added geojson](https://github.com/streeter/bucket-list/blob/master/states.geojson).

**Comment by streeter** [comment]
It's also pretty safe to assume I want to fill out https://github.com/streeter/bucket-list/blob/master/countries.geojson :dart:
